server:
  port: 80

security:
  admin: ${ADMIN_PASS}
spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${GITHUB_CID}
            clientSecret: ${GITHUB_CS}
          google:
            clientId: ${GOOGLE_CID}
            clientSecret: ${GOOGLE_CS}

  #Database Conf
  datasource:
    url: jdbc:postgresql://localhost:15432/connectpeople?currentSchema=public
    username: "admin"
    password: "admin"
    driver-class-name: "org.postgresql.Driver"

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    locations: "db/migration"
    baseline-on-migrate: false

  devtools:
    livereload:
      enabled: true

springdoc:
  swagger-ui:
    path: "/resume/swagger-ui.html"

#logging:
#  level:
#    org.springframework.security: TRACE