server:
  port: ${SERVER_PORT}

spring:

  #Database Conf
  datasource:
    url: jdbc:postgresql://dpg-cehp311gp3jvlf078940-a:15432/connectpeople_6p86?currentSchema=public
    username: "connectuser"
    password: ${DB_PASSWORD}
    driver-class-name: "org.postgresql.Driver"

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    locations: "db/migration"
    baseline-on-migrate: false
springdoc:
  swagger-ui:
    path: "/dev/swagger-ui.html"