server:
  port: 80

spring:
  #Database Conf
  datasource:
    url: jdbc:postgresql://${DB_HOST_HML}/${DB_NAME}?currentSchema=public
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: "org.postgresql.Driver"

    tomcat:
      initial-size: 15
      max-wait: 20000
      max-active: 80
      max-idle: 15
      min-idle: 8
      default-auto-commit: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    locations: "db/migration"
    baseline-on-migrate: false

springdoc:
  swagger-ui:
    path: "/prd/swagger-ui.html"