server:
  port: 8080

spring:

  #Database Conf
  datasource:
    url: jdbc:postgresql://localhost:15432/connectpeople?currentSchema=public
    username: "admin"
    password: "admin"
    driver-class-name: "org.postgresql.Driver"

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    locations: "db/migration"
    baseline-on-migrate: false

springdoc:
  swagger-ui:
    path: "/resume/swagger-ui.html"