CREATE TABLE if not exists resume (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255),
   birth_date date,
   gender INTEGER,
   phone VARCHAR(255),
   cell_phone VARCHAR(255),
   email VARCHAR(255),
   cep VARCHAR(255),
   district VARCHAR(255),
   job_option_one VARCHAR(255),
   job_option_two VARCHAR(255),
   job_option_three VARCHAR(255),
   job_exp_one VARCHAR(255),
   job_exp_two VARCHAR(255),
   job_exp_three VARCHAR(255),
   schooling INTEGER,
   CONSTRAINT pk_resume PRIMARY KEY (id)
);